# Permalinks
permalink:           blogposts/:categories/:title

# Setup
title:               AnalyseThis
tagline:             'Website and blog of Herman Hellenes'
description:         'Computational Physics M.Sc. and Senior Data Scientist at EY.'
url:                 http://herman-hellenes.github.io
baseurl:             ''
highlighter:         rouge

# About/contact
author:
  name:              Herman Hellenes
  email:             herman.hellenes@gmail.com


# Custom vars
version:             1.0.0
