# Permalinks
permalink:           blogposts/:categories/:title

# Setup
title:               
tagline:             'Website and blog of Herman Hellenes'
description:         'Physics M.Sc. and Data Scientist at EY.'
url:                 http://herman-hellenes.github.io
baseurl:             ''
highlighter:         rouge

# About/contact
author:
  name:              Herman Hellenes
  email:             herman.hellenes@gmail.com

# Set up google analytics

analytics :
  provider : google
  google : 
      tracking_id : 'xxx'
  getclicky :
    site_id : xxx

# Custom vars
version:             1.0.0
